news_sites:
  new_york_times:
    url: https://www.nytimes.com
    queries:
      homepage_article_links: '.css-6p6lnl a'
      article_body: '.evys1bk0'
      article_subtitle: '#article-summary'
      article_title: '.css-1vkm6nb h1'
  the_economist:
    url: https://www.economist.com
    queries:
      homepage_article_links: '.headline-link'
      article_body: '.article__body-text'
      article_subtitle: '.article__description'
      article_title: '.article__headline'
  el_universal:
    url: 'https://www.eluniversal.com.mx'
    queries:
      homepage_article_links: '[class*=_Titulo] a'
      article_body: '.gl-Grid_7nota p'
      article_subtitle: '.Encabezado-Articulo h2'
      article_title: '.Encabezado-Articulo h1'
  el_pais:
    url: 'https://elpais.com'
    queries:
      homepage_article_links: '.headline a'
      article_body: '.article_body p'
      article_subtitle: '#article_header h2'
      article_title: '#article_header h1'
